InvalidPathError and InvalidTypeError no longer derive from TypeError
these exceptions are not used for operations that cannot succeed because
of incompatible types. they are really wrong values indicating wrong
api use, which means the code should be fixed.

ValueError cannot be used here since that is already used for
signalling data specific errors.